### ISSUE TITLE
Not able to log in if default admin password wasn't changed

### ISSUE THREAD

**Issue by scheusal333** [BenoitAnastay/paperless-home-assistant-addon#118]
Just installed current version: 1.2.8 for the first time.

did not change the default superuser:
```
username: admin
email: admin@local.dev
password: changeme
```

so i tried to login with unsername: admin and password: changeme

just to get "Username or password is not correct"

from the protocol: 
`...[INFO] [paperless.auth] Login failed for user `admin` from private IP `[my-local-IP]`

I also tried to change the password in the config, with same result.

Do i miss something?

**Comment by BenoitAnastay** [comment]
I'll check my scripts, the intended behaviour is to thrown an error if the user is not defined

In the meanwhile you can delete addon files if it's the first installation then restart it.

When superuser is created there's a message about it in the log

**Comment by scheusal333** [comment]
Thanks for the quick support.

I deleted the Paperless folder in "Addon-configs" 
Changed the password in the addons configuration tab
and restarted the addon.

SUCCESS :)

Also migrating my Documents from other/old paperless addon by copying the folders seems to work just fine.


Thanks for sharing your great work

**Comment by BenoitAnastay** [comment]
Behavior tested, and it works as intended (maybe a setup specific issue)

```
[15:47:22] ERROR: Please change default admin password before running addon
s6-rc: warning: unable to start service init-paperless: command exited 1
s6-rc: info: service init-nginx successfully started
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```
