### ISSUE TITLE
Storing files in external drive `media` folder

### ISSUE THREAD

**Issue by BenoitAnastay** [BenoitAnastay/paperless-home-assistant-addon#120]
Some people were using external hard drive, on the @alexbelgium version of the addon, thus I need to add the ability to customize storage paths.

**Comment by alexbelgium** [comment]
Hi, until this is up, people can install the [Samba NAS](https://github.com/dianlight/hassio-addons) addon which publishes local drivers as SMB, and then mount the SMB using HomeAssistant embedded system

**Comment by BenoitAnastay** [comment]
Hi, thanks I though it was native.

If it works that way I have nothing to change on the addon, ppl can still mount in share folder
