### ISSUE TITLE
Paperless mobile

### ISSUE THREAD

**Issue by Sineiko** [BenoitAnastay/paperless-home-assistant-addon#121]
Hello everyone,

How can I use paperless mobile? I don't understand where I have to set what so that I can use it? Can anyone help me with this?

**Comment by BenoitAnastay** [comment]
Similar to #70 

You need to enable a port or use a reverse proxy to access paperless directly with its own URL and not through ingress.

https://github.com/BenoitAnastay/paperless-home-assistant-addon/issues/70#issuecomment-1906095621
