### ISSUE TITLE
Unable to open any documents and no access through external URL

### ISSUE THREAD

**Issue by creuter27** [BenoitAnastay/paperless-home-assistant-addon#128]
Hello,
thank you for the very nice work!!
I have installed the addon and it works fine except for the 2 issues mentioned in the title.

1. If I open any document then the preview doesn't show. Instead, I get an "Öffnen" Button where the preview should be. If I click that button then a new browser tab opens where the following error message is displayed: "401: Unauthorized" .

2. Accessing the paperless instance through the external URL doesn't work at all. 
I get the following error:
[2024-03-26 13:00:03,606] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://mydomainname does not match any trusted origins.): /api/hassio_ingress/A1Tv2B4Kq17L5uGP-pZM3xtZzzTXgXL65VRG_b2IFMI/accounts/login/

I have set the internal and external URL manually to http://homeassistant.local:8123/ and ttps://mydomainname according to the issues #69 and #72.

That didn't help. According to what I understand in these issues the problem should have been fixed?
Any help would be much appreciated. If possible please provide exact instructions where exactly to change any settings as I didn't understand for some suggestions given in the issues above where and how the suggested settings can be changed.
Thank you!

**Comment by BenoitAnastay** [comment]
You can add your domain to the CSRF allowed list manually or put it as your PAPERLESS_URL, maybe the domains aren't reported correctly (you can check that through logs)

**Comment by creuter27** [comment]
Sorry for asking questions that may sound stupid but where / how can I do that?

**Comment by creuter27** [comment]
There is no such option in the configuration of the addon.
I guess I have to edit a config file somewhere but looking through the files in the studio code server  I can't find any files that seem to have anything to do with the paperless installation.
Which file do I need to edit and where can I find it?

**Comment by creuter27** [comment]
OK I found out how to set the paperless options now. By selecting File -> Open in the Studio code server I could navigate to the addon_config folder where I finally found the paperless files and an example for the paperless.conf.
There I have made a copy of the example file, renamed it to paperless.conf, and set the parameter:

PAPERLESS_URL=https://mydomain,http://homeassistant.local:8123

That has improved the situation in that both the internal and external now behave the same:
I can now login to paperless with both URLs but I still can't preview any documents

**Comment by creuter27** [comment]
Following are all log entries between then end of starting the addon and trying to view / open a document:

[2024-03-26 16:12:18,385] [INFO] [celery.worker.consumer.connection] Connected to redis://localhost:6379//
[2024-03-26 16:12:18,477] [INFO] [celery.apps.worker] celery@ca5234a0-paperless-ngx ready.
/usr/local/lib/python3.11/dist-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
[2024-03-26 16:20:00,002] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-03-26 16:20:00,017] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[70f874d5-e0f6-4378-a3ab-eda460ff2fe0] received
[2024-03-26 16:20:00,210] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[70f874d5-e0f6-4378-a3ab-eda460ff2fe0] succeeded in 0.18919590299992706s: 'No new documents were added.'

**Comment by creuter27** [comment]
In fact the preview in the documents - tab is showing but if I edit the document the document doesn't appear on the right side. See attached screenshots.
<img width="1728" alt="Bildschirmfoto 2024-03-26 um 16 29 43" src="https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/80648179/ad689bb8-2a83-4198-b172-711c78e6a334">
<img width="880" alt="Bildschirmfoto 2024-03-26 um 16 33 03" src="https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/80648179/22fb9c15-efd4-4377-923e-711cc2305517">

**Comment by BenoitAnastay** [comment]
For the document display it's a browser issue 
![Screenshot_20240326-174120](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/45088785/b85c086a-0ccc-4270-8790-eee746d7da80)


For others options it was on add-on configuration tab after checking "display unused options"

**Comment by creuter27** [comment]
This is not the cause. I had seen this option before and had set it as you pointed out:
<img width="1121" alt="Bildschirmfoto 2024-03-26 um 18 46 25" src="https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/80648179/663200d6-5811-41a1-8e10-1ce3a4be058b">

**Comment by BenoitAnastay** [comment]
Your PDF are correctly embeded by Paperless, but your browser doens't load them, its maybe to save resources, I can't help since it's not an issue of Paperless and its addon

**Comment by creuter27** [comment]
OK then I will find the solution myself. Thank you for your help so far.

However, it is incorrect that it is not a problem with the installation.
I have another instance of paperless installed in its own docker environment and with this instance, everything  is working although I use the same browser on the same Macbook to access the 2 instances.
It definitely has something to do with the way the paperless instance is installed.

**Comment by BenoitAnastay** [comment]
Everything load well on my side, do you use HTTPS scheme?

I see that the PDF is embedded but the browser displays a button, I don't know the reason, you can go in thr inspector to see if there's any error or warning

**Comment by BenoitAnastay** [comment]
stale
