### ISSUE TITLE
Can't change PAPERLESS_MEDIA_ROOT with paperless.conf

### ISSUE THREAD

**Issue by m-paulus** [BenoitAnastay/paperless-home-assistant-addon#131]
How can I change PAPERLESS_MEDIA_ROOT? I tried setting it in the paperless.conf file, but the addon does not find my documents.

**Comment by BenoitAnastay** [comment]
There's indeed a priority issue between paperless.conf and addon configuration, I can fix that in the init scripts.

But may I ask you why do you need to change this parameter ?

**Comment by m-paulus** [comment]
I already have an external drive with all of my media mounted elsewhere under /share. I am migrating from Alex Belgium's add-on which allowed me to change this setting and just point it at the documents folder in there.

I don't really _need_ to do this..for now I will just mount the documents folder to /share/paperless/media. I guess it would just be nice so I don't have to add another line to /etc/fstab 🙂

Thanks for the add-on!!

**Comment by HydrelioxGitHub** [comment]
Hello and thank you for your work on Paperless. It could be good to add the priority in the documentation. Like if any parameter is filled in the add-on ui and on the paperless.conf, which one is taken ?
