### ISSUE TITLE
Access to paperless ngx denied since Home Assistant update to 2024-05

### ISSUE THREAD

**Issue by PV-Joe** [BenoitAnastay/paperless-home-assistant-addon#137]
Help!

I can’t  start paperless ngx since updating to Home Assistant 2024-05 this morning. I did not change any configuration.

I get the following error when trying to log in:
![IMG_5272](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/110498562/b6611713-f9e6-4c24-9a1f-b183a5ecc155)

Here is the message from the logfile:

[django.security.csrf] Forbidden (Origin checking failed - null does not match any trusted origins.): /api/hassio_ingress/Gdg4X4Zm_QQu5fOm1N9SCdv1dA1YhdG10xBxDONfgDg/accounts/login/

Please help, as I need to log in desperately.

Thank you in advance
Joe

**Comment by BenoitAnastay** [comment]
I try to add `null` as trusted origin but it doesn't works 

```
ERRORS:
?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found null. See the release notes for details
```

**Comment by 13rian13** [comment]
Same here, I get the exact same message as PV-Joe, when trying to login to Paperless-ngx, since updating to Home Assistant Core 2024-05 yesterday evening ... last successful login was 2 days ago.

Core
2024.5.0
Supervisor
2024.04.4
Operating System
12.2
Frontend
20240404.2

**Comment by ThoHilde** [comment]
Same here, tried to follow the steps in the documentation

`CSRF Validation Failled

There is a validation of domain name used for some requests, those domains are extracted from Internal URL, External URL and Hostname of home assistant.

You can find those settings in the network configuration of Home Assistant

Open your Home Assistant instance and manage your systems network configuration.

When set to automatic, those settings cannot be resolved by the Add-on therefore you might need to setup your Internal and External URL manually`

but it did not help

**Comment by PV-Joe** [comment]
That sounds promising. Thank you for your fast response and the hard work to fix the problem.

Do I have to manually change anything or just wait for an update?

Happy weekend 🔆

**Comment by BenoitAnastay** [comment]
@PV-Joe just wait for the update, I made a minor release just for that PR, so it will be published shortly

**Comment by bartrail** [comment]
> @PV-Joe just wait for the update, I made a minor release just for that PR, so it will be published shortly

That fixes it for me! Thank you so much for the quick response 🚀

**Comment by PV-Joe** [comment]
Just installed the update 2.0.1 and login works 😄 So happy to be able to use this great Addon again. That was a fast fix!
Brilliant work!

**Comment by 13rian13** [comment]
Installed the updated and it works again. Thanks ...
