### ISSUE TITLE
Allow access to media dir for consumption

### ISSUE THREAD

**Issue by torfbolt** [BenoitAnastay/paperless-home-assistant-addon#152]
I would like to use a network folder that is mapped into HA under /media/ as consumption dir. I think the only thing missing for that is adding "media:rw" to the map section in the config.json.

I have implemented & tested this in my version of the addon (see https://github.com/torfbolt/paperless-home-assistant-addon/commit/95bfd627c8bf3caca8b4ada9a43386886d44bdfe), but I would like to switch to your version so I can use the ingress feature.

I also looked at the solution proposed in https://github.com/BenoitAnastay/paperless-home-assistant-addon/issues/120 for storing the paperless-media folder in a different location, but the existing HA internal solution for mounting to /media/ looks much easier and more robust to me.

**Comment by BenoitAnastay** [comment]
The actual workaround is to use Samba share addon and mount the share with paperless name.

I prefer to avoid giving add-ons too much access to the host

**Comment by torfbolt** [comment]
Ok, looks like HA has improved since the last time I tried this and you can now natively mount a network folder into /share/, not only into /media/

**Comment by BenoitAnastay** [comment]
Indeed
