### ISSUE TITLE
HTTP Headers removed, causing CSRF faillure

### ISSUE THREAD

**Issue by treffNIX9815** [BenoitAnastay/paperless-home-assistant-addon#169]
Hello,
thx 4 the great work with this addon. I Love it

Since the last Update to 2.1.0 i get following error after login
![image](https://github.com/user-attachments/assets/118e4104-cf2c-4ae9-a4ad-64c361fcf070)
i access paperless with ip adress at local network. 
What can i do to fix that?

Thx

**Comment by BenoitAnastay** [comment]
its maybe a duplicate of #137 

Can you enable DEBUG and  check your addon logs ?

**Comment by PV-Joe** [comment]
Same here.

**Comment by rafael298** [comment]
Same problem here

**Comment by tobilektri** [comment]
@BenoitAnastay the issue occurs in the current version if you try to login via the open port (in my case: http://192.168.2.207:8011/).
If I open Paperless NGX via ingress the login works without issues

**Comment by BenoitAnastay** [comment]
> Restored Paperless NGX back to v2.06 solved the problem.
It's maybe related to this change https://github.com/BenoitAnastay/paperless-home-assistant-addon/pull/168/files#diff-ac6e0dcab49d60e53dd7357527acfbcaa9bf8d14d08f5d9cef3a5a5212274028R11

I'm using another proxy so my setup bypass this one, I need to pass Origin header

**Comment by BenoitAnastay** [comment]
I try to deploy the fix the fast as I can

**Comment by PV-Joe** [comment]
Fixed with 2.1.1
Great! Many thy!

**Comment by treffNIX9815** [comment]
sorry 4 the late answer, but you guys are very fast! :)

THX 4 fixing
