### ISSUE TITLE
Request failed: unauthorized (401)

### ISSUE THREAD

**Issue by Marow** [BenoitAnastay/paperless-home-assistant-addon#170]
Hi, when i will upload an Scan with my iPhone, i get that error message `Request failed: unauthorized (401)`

It was working 2 days ago. I didnt changed something? Probably the last update changed anything?
I checked if the token exists and its there.

If i check the Log of the Addon, i see that, everytime when i try to upload:
`[2024-08-28 10:38:38,716] [WARNING] [django.request] Unauthorized: /api/search/autocomplete/`

Thats all i see. Not possible to connect to the paperless for me anymore and the token is correct.

Current Addon Version:  2.1.0
HA Core Version: 2024.8.3
Supervisor: 2024.08.0

**Comment by Marow** [comment]
With 2.0.6 it was running, its since the update

**Comment by tobilektri** [comment]
Most likely duplicate of #169

**Comment by BenoitAnastay** [comment]
Should be fixed with the lastest update (2.1.1)
I was a bit paranoid when I added ingress authentication and I removed all clients headers on the direct access proxy 😅

**Comment by PV-Joe** [comment]
Many thx for the extra fast fix.
It's working well with 2.1.1
👍

**Comment by BenoitAnastay** [comment]
@Marow Please close this issue if 2.1.1 solved this
