### ISSUE TITLE
Consider Moving the document folder into the addon_config directory

### ISSUE THREAD

**Issue by paviro** [BenoitAnastay/paperless-home-assistant-addon#199]
Hi!
Historically it has been nice to be able to access the documents via the share folder but when having multiple addons that store there data there (Nextcloud does too for example) it's impossible to create a clean snapshot only containing all Paperless data.

If I for example want to create a daily backup of my Paperless documents but only a weekly one of Nextcloud this is currently impossible which is unfortunate as both contain huge amounts of data.

I think it would be good to consider moving the documents into the addon_config directory so a clean snapshot can be created.

Best,
Paul

**Comment by paviro** [comment]
Solved this by not backing up the share folder at all in snapshots and instead backing it up separately which is even cleaner and doesn't create huge snapshots.

**Comment by BenoitAnastay** [comment]
Anyway it's intended that the backup save the paperless content and the share folder is also required to be able to mount remote storage.

It's more a Home Assistant issue about how it handle backups and storage mounting
