### ISSUE TITLE
CLI tools not working correctly when using the paperless.conf in addon_config

### ISSUE THREAD

**Issue by paviro** [BenoitAnastay/paperless-home-assistant-addon#202]
Hi there,
I configured MariaDB in the `paperless.conf` and paperless correctly uses it. When I tried to import my documents with the document importer it used the old SQLLite database however until I adjusted the file `/usr/src/paperless/paperless.conf` to also have the MariaDB info in there.

Could it be adjusted that the CLI tools also use the changes from the addon_config paperless.conf?

Best,
Paul

**Comment by paviro** [comment]
That seems to work yes! Thank you!

**Comment by BenoitAnastay** [comment]
Thanks I'll add this to the next update
