### ISSUE TITLE
Configuration of Username and Passwort

### ISSUE THREAD

**Issue by TWuerdemann** [BenoitAnastay/paperless-home-assistant-addon#3]
Setting the inital username and passord of the superuser in the configuration does not work.
User is unknown according to the first login trys.

Did I miss something? If so I think that has to be clarified in the Readme.

Cheers :)

**Comment by BenoitAnastay** [comment]
I fixed serval first start issue, you can update to v1.17.4e and check your configuration (because I simplified the options)

Thank you for your report.

**Comment by TWuerdemann** [comment]
Works perfectly. Thanks a lot
