### ISSUE TITLE
Use OCR language not installed by default

### ISSUE THREAD

**Issue by niklasfyi** [BenoitAnastay/paperless-home-assistant-addon#4]
It is not possible to use NOR (Norwegian) as an OCR language, as it is not installed by default. 

I think there is a config parameter missing.

**Comment by BenoitAnastay** [comment]
The configuration parameter is 'language'

The availables languages are listed here https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html

The list of languages is space separated.

I'll check if it's working the intended way

**Comment by BenoitAnastay** [comment]
Indeed the optional languages aren't installed automatically.

```ERRORS:
?: The selected ocr language nor is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.```

I'll take care of that issue tomorrow since it's 2am here

**Comment by BenoitAnastay** [comment]
The last release fixed the issue, you have now both primary language setting and the list of languages to install.

Can you confirm me that it's working ?

**Comment by niklasfyi** [comment]
Starts without OCR problems 👍
Thanks for the quick fix.
