### ISSUE TITLE
settings PAPERLESS_CONSUMER_RECURSIVE and PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS

### ISSUE THREAD

**Issue by am78** [BenoitAnastay/paperless-home-assistant-addon#40]
Hi,
I really like your integration, so far it works quite nice on my rpi4.
What I'm missing are these options for an initial import of my folder based document structure:
PAPERLESS_CONSUMER_RECURSIVE and PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
description here: https://docs.paperless-ngx.com/configuration/#PAPERLESS_CONSUMER_RECURSIVE

Both are false by default and I couldn't find any way to set them to true.

Would be great to be able to set these options.
Thanks,
Michael

**Comment by am78** [comment]
@BenoitAnastay thank you so much for the fast reaction. Just tested the options and it seems to work as expected.

**Comment by BenoitAnastay** [comment]
You're welcome, 
I was already preparing the v1.0.0 release when you asked.
