### ISSUE TITLE
Error message CSRF Failed - plugin version 1.1.1

### ISSUE THREAD

**Issue by sahnetorti** [BenoitAnastay/paperless-home-assistant-addon#61]
I have updated today to version 1.1.1 of the plugin.
First off, everything looks OK but when I tried to change a setting (name of a saved view) I got an error message, see below.
It probably is some configuration issue, but I cannot find anything in the documentation of the add-on and homeassistant. Neither a google search provided good resources.

This is with accessing paperless through the URL:
`http://homeassistant.local:8123/hassio/ingress/ca5234a0_paperless-ngx`

Error message:
```
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":403,"statusText":"Forbidden","url":"http://homeassistant.local:8123/api/hassio_ingress/c9w93rKVWvLjAS5nnaXz7ACFa_daeCZTPTv9Xnz8-xw/api/ui_settings/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://homeassistant.local:8123/api/hassio_ingress/c9w93rKVWvLjAS5nnaXz7ACFa_daeCZTPTv9Xnz8-xw/api/ui_settings/: 403 Forbidden","error":{"detail":"CSRF Failed: Origin checking failed - http://homeassistant.local:8123 does not match any trusted origins."}}
```

When I try with the IP address in the URL like this:
`http://192.168.0.68:8123/ca5234a0_paperless-ngx/ingress`
I get the login-screen and after logging in the same message:
```
Verboten (403)
CSRF-Verifizierung fehlgeschlagen. Anfrage abgebrochen.
Mehr Information ist verfügbar mit DEBUG=True.
```
which translates to the same issue above.

**Comment by BenoitAnastay** [comment]
You need to set your PAPERLESS_URL to http://home assistant.local

I keep your issue open, I'll make it automatic

**Comment by schwurbelli** [comment]
Ok, tried it and got it working. Thanks Benoit. 

Two comments for everybody landing here:
- url has to be without / at the end 
- For me, it only worked with http://ipadressofHA:8123

using http://homeassistant.local:8123 did bot work in my network configuration. 

Could you make the PAPERLESS_URL mandatory in GUI addon configuration?

**Comment by BenoitAnastay** [comment]
> Could you make the PAPERLESS_URL mandatory in GUI addon configuration?

I'll get IPs and URLs set in Home Assistant and add them to allowed CSRF for both HTTPS and HTTP scheme 
That way it will be transparent for the ends user, the PAPERLESS_URL option will remains for custom domains settings

**Comment by sahnetorti** [comment]
Setting the PAPERLESS_URL worked for me, too. Thanks for the help!
