### ISSUE TITLE
Hostname (homeassistant.local) not resolved as allowed URL

### ISSUE THREAD

**Issue by MelleD** [BenoitAnastay/paperless-home-assistant-addon#69]
Hi @BenoitAnastay,

thanks for this Add-On :).

I am currently try it our and cannot login, cause of this error.
Can you give me a hint what is wrong?

[2024-01-22 17:28:47,227] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - http://homeassistant.local:8123 does not match any trusted origins.):

**Comment by MelleD** [comment]
Set the paperless url to: http://homeassistant.local:8123

Then it works :)

**Comment by BenoitAnastay** [comment]
Its should be set automatically from internal_url setting

What are the Home Assistant URL set here ? 
https://my.home-assistant.io/redirect/network/

**Comment by MelleD** [comment]
@BenoitAnastay thanks for your quick answer:

I'm just using the default:
Hostname: homeassistant
Local Network: Automatic

**Comment by BenoitAnastay** [comment]
Thanks, it's maybe an issue with Home Assistant, I'll try to investigate that

**Comment by BenoitAnastay** [comment]
So in your case it's the hostaname appended with `.local:8123` (https://github.com/home-assistant/cli/blob/c1ab453cabe154729a88c165c63a41c575c30c11/cmd/banner.go#L162)

I'll add this URL to the list of allowed URLs
