### ISSUE TITLE
📚 Ingress and API authentification

### ISSUE THREAD

**Issue by MelleD** [BenoitAnastay/paperless-home-assistant-addon#70]
Hello, 

do you use a third party app to upload, e.g. Paperparrot or Paperless Swift?
https://github.com/paperless-ngx/paperless-ngx/wiki/Affiliated-Projects

I tried to add a long living bearer token in HA and include it as a header in the request. But unfortunately I can't get through. Can I access the paperless UI without going to home assistant?

**Comment by BenoitAnastay** [comment]
Yes, you will have to go on the addon configuration tab then enable a port.

There is no way to disable Home Assistant auth for an ingress endpoint such as API, that why we need to enable direct access.

If I add the HA auth to Paperless through ingress i'll probably add a port that will only be usable for API

**Comment by MelleD** [comment]
@BenoitAnastay thanks let me try :)

**Comment by BenoitAnastay** [comment]
Have you updated the add-on to the last release?

**Comment by BenoitAnastay** [comment]
My apologies, it wasn't pushed to the repository, I don't know why

**Comment by MelleD** [comment]
No problem. When it's available I'll test the new version :)

**Comment by BenoitAnastay** [comment]
It's updated, there was a weird bug on GitHub side 1.1.2 was stuck as last release even though 1.2.3 was tagged last 🤔🤷‍♂️

**Comment by MelleD** [comment]
Works thank you a lot

**Comment by MelleD** [comment]
<img width="694" alt="Bildschirmfoto 2024-01-23 um 18 25 22" src="https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/6340898/7f1bc329-7fc8-4b6a-9c53-12d80642d590">

Interesting one if i have no token and login directly. I get this error (maybe this is the issue why i get no connection from the mobile app).

If I use first the HA instance and login it works

**Comment by BenoitAnastay** [comment]
It's #69 issue.

On network configuration https://my.home-assistant.io/redirect/network/

You can manually set internal URL to http://homeassistant.local:8123

Then restart home assistant, you may need to do the same for external_url it will also extract base host to set the direct access to the list of allowed URLs

**Comment by MelleD** [comment]
And if add as URL: http://homeassistant.local:7071/ then it's the other way around :).

**Comment by MelleD** [comment]
> It's #69 issue.

Are you sure?
Maybe i have just to set this
https://docs.paperless-ngx.com/configuration/#PAPERLESS_CSRF_TRUSTED_ORIGINS
to http://homeassistant.local:8123/,http://homeassistant.local:7071

**Comment by BenoitAnastay** [comment]
There's a script integrated that will set this automatically using defined external url and internal url 

https://github.com/BenoitAnastay/paperless-home-assistant-addon/blob/33fb5f3f0bb464af8a8850d0e66f4b4e5d0c6108/paperless-ngx/rootfs/etc/s6-overlay/s6-rc.d/init-paperless/run#L33-L37

**Comment by MelleD** [comment]
Iam not using the external url, because my instance is just locally available or with the internal url over VPN (tailscale)

so IMHO whart is missing, is when a port is set the in the config also to add this url

e.g. internal url + defined port in my case http://homeassistant.local:7071

**Comment by BenoitAnastay** [comment]
> The addon port is in my case the 7071, correct?

Yes it's taking the value form the one you put in your addon configuration

**Comment by MelleD** [comment]
Ok got it. 
Then I think with the issue https://github.com/BenoitAnastay/paperless-home-assistant-addon/issues/69 there are two missing urls.
a) the url with .local and default port (8123)
b) the url with .local and add on port


As long as that isn't fixed, I'll try it myself. But now I can't log in at all. Now I'm confused :D
`PAPERLESS_CSRF_TRUSTED_ORIGINS=http://homeassistant.local:8123,http://homeassistant.local:7071`

**Comment by BenoitAnastay** [comment]
This setting can be set in `/addons_config/ca5234a0_paperless-ngx/paperless.conf`

> there are two missing urls
This is already the case it does extract the host and use both schemes and ports, I just forgot to add `.local` to hostname

It should also work with IPs

**Comment by MelleD** [comment]
> This setting can be set in `/addons_config/ca5234a0_paperless-ngx/paperless.conf`

Yes I know I also set this `PAPERLESS_OCR_USER_ARGS={"invalidate_digital_signatures": true}`. This worked, but not the `PAPERLESS_CSRF_TRUSTED_ORIGINS`. 

> It should also work with IPs

You are right, then 4 :)

**Comment by BenoitAnastay** [comment]
You can enable DEBUG to have a more verbose error message

**Comment by MelleD** [comment]
I have no luck so far with the config file. Maybe I just wait for your fix and test again.
"Paper Less" app works so far. The other two are not working but one should be enough :D...
I have just a limit to upload files >10MB was not working. I think this a nginx limit body size limit, correct?

**Comment by BenoitAnastay** [comment]
I'll open another issue for nginx upload limit, the #69 is planned to be fixed with tomorrow update
