### ISSUE TITLE
🐛 Nginx client_max_body_size limited

### ISSUE THREAD

**Issue by BenoitAnastay** [BenoitAnastay/paperless-home-assistant-addon#73]
I have no luck so far with the config file. Maybe I just wait for your fix and test again.
              "Paper Less" app works so far. The other two are not working but one should be enough :D...
              I have just a limit to upload files >10MB was not working. I think this a nginx limit body size limit, correct?

_Originally posted by @MelleD in https://github.com/BenoitAnastay/paperless-home-assistant-addon/issues/70#issuecomment-1908989235_

**Comment by MelleD** [comment]
You are fast :). Thanks

Do you think it's possible to make this customizable with a property?

**Comment by BenoitAnastay** [comment]
> Do you think it's possible to make this customizable with a property?

Yes
