### ISSUE TITLE
[Feature Request] Add Home Assistant shortname as allowed domain

### ISSUE THREAD

**Issue by MelleD** [BenoitAnastay/paperless-home-assistant-addon#81]
In Tailscale there is a magic DNS resolution for the URL (https://tailscale.com/kb/1081/magicdns). Unfortunately it is not compatible with `homeassistant.local` because
a) The default setting uses `homeassistant` as DNS without local
b) Only dashes and no dots are allowed in the hostname

With the new setting CSRF trusted domain you can set the url http://homeassistant:port. This is working as well :).
Maybe it's worth considering introducing a checkbox "Enable tailscale magic dns" in the config to automatically determine the url.

**Comment by BenoitAnastay** [comment]
I'm not sure to understand, the URL isn't dynamic, so why not adding as main URL ?

There's no validation regex for domains on my addon 

![CSRF-setting](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/45088785/5ce9854e-d424-4532-8834-fd78004e5f1f)

I'm not using it that way because it's braking TLS resolution 
![SSL-broken](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/45088785/31425459-0669-4f55-ab0b-fc31bc607834)

I haven't added RAW urls options for CSRF but domains because I was thinking that people who will use a domain dedicated to paperless (not share with HA) would set is as Paperless URL

**Comment by MelleD** [comment]
How I said it's also working with trusted domain.
![Uploading Bildschirmfoto 2024-01-29 um 20.47.52.png…]()

The internal hostname address is with local (what you figured out here)
See here: https://github.com/home-assistant/cli/blob/c1ab453cabe154729a88c165c63a41c575c30c11/cmd/banner.go#L162

But the tailscale VPN address is without local
<img width="505" alt="Bildschirmfoto 2024-01-29 um 20 51 01" src="https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/6340898/e1379">


And dot is not allowed
<img width="511" alt="Bildschirmfoto 2024-01-29 um 20 51 27" src="https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/6340898/c648158b-6b88-4be5-b8cd-5ed232164efd">
5cc-5236-4736-adbb-a97d6a9cd199">

It's just nicer for external tailscale use also add the trusted domain without local or internal adress without .local.
I think this just relevant when you use Tailscale VPN.

**Comment by BenoitAnastay** [comment]
You can add homeassistant.local as CSRF allowed and https://homeassistant as Paperless URL then

**Comment by MelleD** [comment]
> You can add homeassistant.local as CSRF allowed and https://homeassistant as Paperless URL then

My setting works with the trusted domain. All is fine.

The url automatically for tailscale would just be a shortcut and easier for some people. Not more :). With current settings all is fine so far.

**Comment by BenoitAnastay** [comment]
> My setting works with the trusted domain. All is fine.

It shouldn't have worked that way so I'll try to allow both domains and raw urls to be added in the next release

**Comment by MelleD** [comment]
> It shouldn't have worked that way so I'll try to allow both domains and raw urls to be added in the next release

Okay, now I'm confused. Why shouldn't it have worked?

In my internal network i use the default url:
http://homeassistant.local:8123/xxx/ingress
This was added with the last release:

My "external" VPN link is
http://homeassistant:8123/xxx/ingress

So i just added homeassistant to the trusted domain. Works pretty well.

For the mobile apps I added a port (this was you see in the picture), because of the authorization with HA. So I added the port 7071.
So in my Tailscale VPN the url is: http://homeassistant:7071 and this I added to the trusted domains. So why not? Looks straight forward to me :)?

**Comment by BenoitAnastay** [comment]
Yes indeed, it works that way

I thought full URLs were "http://homeassistant/" and "http://homeassistant.local:8123/"

And because my script append ports to domains it will allow http://homeassistant:7071/ and http://homeassistant:8123/ by addin homeassistant to allowed domains 

The input is a domain, you put an URL but it's trimmed by my script, so if you were using a proxy to use domain without a port it does only works when using Paperless_URL option

**Comment by MelleD** [comment]
Ok yes, I think with Tailscale and VPN it's a simple setup also for the hostname. So therefore was just my idea to add a checkbox for Tailscale user instead of typing the "the magic dns" hostname manually as url or domain. This was just the small feature idea :)

**Comment by BenoitAnastay** [comment]
The problem is if I add an option for tailscape DNS you can either have someone using another short name like http://paperless or someone using others third party softwares, and I try the minimal required options to avoid cluttering

**Comment by MelleD** [comment]
It's fine was just an idea. Yes off course you can have multiple option for different third party software, but the DNS magic name looked very simple to figure out :). And a small checkbox to use or not use looked okay for me.

Maybe you'll use Tailscale at some point and think it's a great idea, then you can reopen the ticket ;)

**Comment by BenoitAnastay** [comment]
I can indeed add shortname of the homeassistant hostaname by default, it was the case before I figured out they hard coded .local suffix 

On some networks homeassistant.local can also be resolved as https://homeassistant but shortnames seem to be less commonly used

**Comment by MelleD** [comment]
> On some networks homeassistant.local can also be resolved as https://homeassistant/ but shortnames seem to be less commonly used

In my local network it's not working with the default settings. It just works in my VPN, but with port and without https (not necessary in VPN)
So in VPN it's http://homeassistant:8123 and with own port http://homeassistant:port(7071)
