### ISSUE TITLE
🦺 No input validation for admin login and password configuration

### ISSUE THREAD

**Issue by themex85** [BenoitAnastay/paperless-home-assistant-addon#83]
Hallo I hope someone could help me,

i installed the paperless home assistant addon.

If i try to login, I allways get the message that username and password are not matching. 

in German:
"Ihr Benutzername und Kennwort stimmen nicht überein. Bitte versuchen Sie es erneut."

Log says this: 
2024-01-30 20:51:41,150] [INFO] [paperless.auth] Login failed for user `xxx` from private IP 

I deinstalled and reinstallad the addon several times. and tried other Superuser names.

Is there anything I could do?

Kind regards Max

**Comment by BenoitAnastay** [comment]
If you forgot to edit configuration before starting the add-on it might be set to null null

I'll add an input validation to avoid that

In the meanwhile you can either try to connect to null account or delete the add on configuration folder
