### ISSUE TITLE
Origin checking failed - https://xyz.de does not match any trusted origins

### ISSUE THREAD

**Issue by daloki83** [BenoitAnastay/paperless-home-assistant-addon#87]
Hello,

1st of all---localy everything is fine and i love the add-on! 

The problem only happens when i try to access PL-NGX from external (www)
My setup looks like:

- Add-On: Cloudflared installed and configured to my real (external) domain
- I can login into HA and do everything except PL-NGX
I tried so many configurations within "192.168.178.72/addon_configs/ca5234a0_paperless-ngx/paperless.conf" (Btw. why not making these configs available in the UI?)
like setting PAPERLESS_URL, PAPERLESS_CSRF_TRUSTED_ORIGINS, PAPERLESS_ALLOWED_HOSTS to my external domain, internal IP etc. but at the end i'm not able to login to PL-NGX and i get always this error message:

[django.security.csrf] Forbidden (Origin checking failed - https://xyz.de does not match any trusted origins.)

I have the feeling that the "PAPERLESS_CSRF_TRUSTED_ORIGINS" setting is completly ignored.

Can you support please?

**Comment by BenoitAnastay** [comment]
You must check this box 
![Screenshot_20240211-214940](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/45088785/db76d1ff-8da9-452b-bcd1-60261385de9e)

**Comment by daloki83** [comment]
OMG!!! I was so blind... Thanks...works like a charm
