### ISSUE TITLE
Worker exited prematurely: signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by rybe** [BenoitAnastay/paperless-home-assistant-addon#94]
When trying to process a file via the Consumption folder. I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT) Job: 2.
```

Is there a solution here?

Many thanks for your support!

**Comment by BenoitAnastay** [comment]
It's weird, can you provide me more context, logs?

**Comment by rybe** [comment]
I'm sorry, I should have analyzed the problem in more detail first.
It is due to the options "Barcodes consuming" and "ASN Barcodes". If there is a barcode on the scanned document, it throws Paperless Ngx off track and the error message appears.

It is a problem with Paperless Ngx, not with the Home Assistant Add In.
