### ISSUE TITLE
upload file size limited to 30M

### ISSUE THREAD

**Issue by buttonger** [BenoitAnastay/paperless-home-assistant-addon#95]
where is the conf-file to setup the file size limit?

**Comment by BenoitAnastay** [comment]
It's on the add-on configuration tab 
![Screenshot_20240218-145952](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/45088785/126cf5c0-af2a-41a7-a62d-6a98b6220a12)

**Comment by buttonger** [comment]
Thank you very much.

**Comment by buttonger** [comment]
Thank you very much.
