### ISSUE TITLE
media and consume directory not found when mounted as nfs

### ISSUE THREAD

**Issue by mopahle** [BenoitAnastay/paperless-home-assistant-addon#96]
I created a nfs network share with name "paperless" and usage "share". When starting paperless-ngx addon i see the following error message in the logs: 
```
?: PAPERLESS_CONSUMPTION_DIR is set but doesn't exist.
	HINT: Create a directory at /share/paperless/consume
?: PAPERLESS_MEDIA_ROOT is set but doesn't exist.
	HINT: Create a directory at /share/paperless/media
```

the metioned folders do exist on the host. When I remove the network share, the addon starts without any issues.

**Comment by BenoitAnastay** [comment]
When you mount the storage can you explore it from Home Assistant OS ?

It's generally ACL issue on your remote host, whan you can try is to disable the ACL so paperless will have unrestricted access to the share

**Comment by BenoitAnastay** [comment]
> How can I disable the ACL?

I don't known it on your storage server 


You can also use docker exec into the add-on container to check if there's any error.

Look at your network share logs also you may have some clues

**Comment by mopahle** [comment]
docker exec into the container helps me to solve the issue now: Inside the container the /share/paperless directory has no privileges. I changed this with chmod 0777 /share/paperless inside the container (on the host the privileges were already at 0777) and now the addon starts normally. I have no clue about the root cause.
Thanks for pointing me into the right direction.

**Comment by BenoitAnastay** [comment]
Thanks you, I'll add a chown command to the init script as an attempt to fix this issue
